### ISSUE TITLE
FontAwesome icons not working

### ISSUE THREAD

**Issue by Ciferlingvulo** [AlxMedia/indite#1]
Hello,

First, let me congratulate you for your work on all your themes, I love them.

I've recently installed Indite, and I added some social accounts icons. But for some reason, two of them don't seem to work : 
```html
<i class="fab fa-instagram">
<i class="fab fa-youtube">
```

The others I'm using work fine : 
```html
<i class="fab fa-discourse">
<i class="fab fa-discord"></i>
<i class="fab fa-twitter"></i>
```

Both the problematic ones seem to exist in FontAwesome 5, and I don't see what could be wrong with the code. So I'm assuming the problem comes from the theme.
Could you have a look please ?
And forgive me in advance if in the end it was a mistake of mine...

Regards.

EDIT : 2min later I just found what was wrong... My adblock was removing them...
Sorry for the useless issue!

**Comment by AlxMedia** [comment]
Thanks for sharing the solution! I was just reading this and scratching my head what could be wrong :-)
